### ISSUE TITLE
GET handler

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/esp32-edge-firmware#6]
Write handler to create endpoints for GET requests. 

A user (ie. a web app) should be able to get a response when requesting endpoints matching the [thingset data structure](https://libre.solar/thingset/2a_general.html#data-structure). A successful request means that the endpoint exists (ie. /data/output/Bat_V or /pub/Bat_A). With a successful request the user should receive a json response, otherwise a 40x status code.

**Comment by martinjaeger** [comment]
First version was implemented in commits d0df27d8a867fb94cae3214cbaffa721138093c0 and 0c15c06b35a5630bd72fcfeb4ffe21338d783205.

The output data nodes of the device connected via serial is now accessible via http://data-manager-ip/ts/serial/output.

**Comment by Gretel5X** [comment]
@martinjaeger I think this can be closed now? PR #11 did all that

**Comment by martinjaeger** [comment]
Agreed.
